name: Build
on:
#  pull_request:
  push:
    branches:
      - main

jobs:
  build_webapp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: install dependencies
        working-directory: ./webapp
        run: |
          npm ci

      - name: build webapp
        working-directory: ./webapp
        run: |
          npm run build

  build_backend:
    services:
      cassandra:
        image: cassandra:latest
        ports:
          - 9042:9042

    defaults:
      run:
        working-directory: ./backend

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: run unit tests
        run: |
          ./gradlew test

      - name: build jar
        run: |
          ./gradlew :app:shadowJar

      - name: run app
        env:
          KTOR_ENV: ci
        run: java -jar app/build/libs/*.jar &

      - name: execute api tests
        run: ./gradlew :api-tests:integrationTest

      - name: archive api tests results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: api-tests-results
          path: backend/api-tests/build/reports/tests/integrationTest
