name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Build
        working-directory: ./backend
        run: |
          ./gradlew :app:shadowJar

  build_webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies
        working-directory: ./webapp
        run: |
          npm ci

      - name: Build
        working-directory: ./webapp
        run: |
          npm run build


  #  publish_backend:
  #    needs: [ build_backend ]
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@v1
  #
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v1
  #
  #      - name: Login to DockerHub
  #        uses: docker/login-action@v1
  #        with:
  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
  #          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #      - name: Build backend and push
  #        uses: docker/build-push-action@v2
  #        with:
  #          context: ./backend
  #          push: true
  #          tags: piotrwest/ak-backend:latest
  #
  #  publish_webapp:
  #    needs: [ build_webapp ]
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Set up QEMU
  #        uses: docker/setup-qemu-action@v1
  #
  #      - name: Set up Docker Buildx
  #        uses: docker/setup-buildx-action@v1
  #
  #      - name: Login to DockerHub
  #        uses: docker/login-action@v1
  #        with:
  #          username: ${{ secrets.DOCKERHUB_USERNAME }}
  #          password: ${{ secrets.DOCKERHUB_TOKEN }}
  #
  #      - name: Build webapp and push
  #        uses: docker/build-push-action@v2
  #        with:
  #          context: ./webapp
  #          push: true
  #          tags: piotrwest/ak-webapp:latest

  deploy:
    needs: [build_backend, build_webapp]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.WESTUS00_KEY }}

      - name: Deploy app to westus00
        run: |
          ssh -T -o StrictHostKeyChecking=no -l ${{ secrets.WESTUS00_USER }} ${{ secrets.WESTUS00_ADDRESS }} << EOF
            cd ~/app
            git fetch
            git reset --hard origin/main
            docker-compose up --build --force-recreate -d
            docker image prune -f
          EOF
