name: Deploy to westus00
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CONNECT_BUNDLE_FILE_NAME: secure-connect.zip

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.WESTUS00_KEY }}

      - name: download cassandra secure bundle
        run: |
          curl -s ${{ secrets.CASSANDRA_SECURE_BUNDLE_URL }} > ${{ env.CONNECT_BUNDLE_FILE_NAME }}

      - name: copy cassandra secure bundle to westus00
        run: |
          scp -o StrictHostKeyChecking=no ${{ env.CONNECT_BUNDLE_FILE_NAME }} ${{ secrets.WESTUS00_USER }}@${{ secrets.WESTUS00_ADDRESS }}:

      - name: deploy app to westus00
        env:
          ASTRA_DB_USERNAME: ${{ secrets.ASTRA_DB_USERNAME }}
          ASTRA_DB_PASSWORD: ${{ secrets.ASTRA_DB_PASSWORD }}
          ASTRA_DB_SECURE_CONNECT_BUNDLE_PATH: ${{env.CONNECT_BUNDLE_FILE_NAME}}
        run: |
          ssh -T -o StrictHostKeyChecking=no -l ${{ secrets.WESTUS00_USER }} ${{ secrets.WESTUS00_ADDRESS }} << EOF       
            cd ~/app
            git fetch
            git reset --hard origin/main
          
            echo "ASTRA_DB_SECURE_CONNECT_BUNDLE_PATH=$ASTRA_DB_SECURE_CONNECT_BUNDLE_PATH" >> .env.prod
            echo "ASTRA_DB_USERNAME=$ASTRA_DB_USERNAME" >> .env.prod
            echo "ASTRA_DB_PASSWORD=$ASTRA_DB_PASSWORD" >> .env.prod
          
            mv ~/$CONNECT_BUNDLE_FILE_NAME ~/app
            docker-compose -f docker-compose.yml -f prod.yml up --build --force-recreate -d
            docker image prune -f
          EOF
